MyFinances/Controllers/BillsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MyFinances.Models;
using Microsoft.AspNet.Identity;
using MyFinances;
using MyFinances.Controllers;

namespace Finances.Controllers
{
    [Authorize]
    public class BillsController : BaseController
    {
        public ActionResult Index (bool showInactive = false)
        {
            ViewBag.ShowInactive = showInactive;
            return View(GetBills(showInactive));
        }

        public ActionResult Details (int? id)
        {
            ViewBag.Action = "Details";
            Bill bill = GetBill(id);
            if (bill == null)
            {
                return HttpNotFound();
            }
            return View(bill);
        }

        public ActionResult Create ()
        {
            ViewBag.Action = "Create";
            ViewBag.Users = GetAvailableUsers();
            ViewBag.SharedPercentage = Enum.GetValues(typeof(SharedPercentage));
            return View("Details", new Bill());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create (string[] payeeId, string[] sharedPercent, [Bind(Include = "Name,DueDate,Amount,Payee,IsDueDateStaysSame,IsAmountStaysSame,IsShared,PaymentFrequency")] Bill bill)
        {
            ViewBag.Action = "Create";
            if (ModelState.IsValid)
            {
                bill.User = db.Users.Find(user.Id);
                db.Bills.Add(bill);
                UpdateBillShared(bill, payeeId, sharedPercent);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Users = GetAvailableUsers();
            ViewBag.SharedPercentage = Enum.GetValues(typeof(SharedPercentage));
            return View("Details", bill);
        }

        public ActionResult Edit (int? id)
        {
            ViewBag.Action = "Edit";
            Bill bill = GetBill(id);
            if (bill == null || bill.User.Id != user.Id)
            {
                return HttpNotFound();
            }
            ViewBag.Users = GetAvailableUsers();
            ViewBag.SharedPercentage = Enum.GetValues(typeof(SharedPercentage));
            return View("Details", bill);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit (string[] payeeId, string[] sharedPercent, [Bind(Include = "ID,Name,DueDate,Amount,Payee,IsDueDateStaysSame,IsAmountStaysSame,IsShared,PaymentFrequency")] Bill subBill)
        {
            ViewBag.Action = "Edit";
            Bill bill = db.Bills.Find(subBill.ID);
            if (bill == null || bill.User.Id != user.Id)
            {
                return HttpNotFound();
            }
            bill = bill.MapSubmit(subBill).Populate(user);
            if (ModelState.IsValid)
            {
                db.Entry(bill).State = EntityState.Modified;
                UpdateBillShared(bill, payeeId, sharedPercent);
                db.SaveChanges();
                return RedirectToAction("Details", new { id = bill.ID });
            }
            ViewBag.Users = GetAvailableUsers();
            ViewBag.SharedPercentage = Enum.GetValues(typeof(SharedPercentage));
            return View("Details", bill);
        }

        public ActionResult Deactivate(int? id)
        {
            Bill bill = GetBill(id);
            if (bill == null || bill.User.Id != user.Id)
            {
                return HttpNotFound();
            }
            bill.IsActive = false;
            db.Entry(bill).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Activate (int? id)
        {
            Bill bill = GetBill(id);
            if (bill == null || bill.User.Id != user.Id)
            {
                return HttpNotFound();
            }
            bill.IsActive = true;
            db.Entry(bill).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Details", new { id = bill.ID });
        }
        
        public ActionResult Delete(int? id)
        {
            Bill bill = GetBill(id);
            if (bill == null || bill.User.Id != user.Id)
            {
                return HttpNotFound();
            }
            bill.SharedWith.ToList().ForEach(x => db.SharedBill.Remove(x));
            if (bill.BillPayments.Any())
            {
                bill.BillPayments.ToList().ForEach(x => db.SharedBillPayment.RemoveRange(x.SharedWith));
                db.BillPayments.RemoveRange(bill.BillPayments);
            }
            db.Bills.Remove(bill);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult AddPayment(int? id)
        {
            ViewBag.Action = "Add Payment";
            Bill bill = GetBill(id);
            if (bill == null || bill.User.Id != user.Id)
            {
                return HttpNotFound();
            }

            BillPayment payment = new BillPayment
            {
                Amount = bill.Amount,
                DatePaid = bill.DueDate,
                Payee = bill.Payee,
                Bill = bill
            };
            
            
            ViewBag.Users = GetAvailableUsers(payment.Bill);
            ViewBag.SharedPercentage = Enum.GetValues(typeof(SharedPercentage));
            return View("Payment", payment);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddPayment (int? id, string[] payeeId, string[] sharedPercent, [Bind(Include = "Amount,DatePaid,Payee")] BillPayment billPayment)
        {
            ViewBag.Action = "Add Payment";
            billPayment.Bill = GetBill(id);
            if (billPayment == null || billPayment.Bill.User.Id != user.Id)
            {
                return HttpNotFound();
            }
            if (ModelState.IsValid)
            {
                billPayment.User = db.Users.Find(user.Id);
                db.BillPayments.Add(billPayment);
                db.Entry(SaveBillForNextPayment(billPayment)).State = EntityState.Modified;
                UpdateBillPaymentShared(billPayment, payeeId, sharedPercent);
                db.SaveChanges();
                return RedirectToAction("Details", new { id = billPayment.Bill.ID });
            }
            ViewBag.Users = GetAvailableUsers(billPayment.Bill);
            ViewBag.SharedPercentage = Enum.GetValues(typeof(SharedPercentage));
            return View("Payment", billPayment);
        }

        public ActionResult EditPayment (int? id)
        {
            ViewBag.Action = "Edit Payment";
            BillPayment billPayment = GetBillPayment(id);
            if (billPayment == null || billPayment.User.Id != user.Id)
            {
                return HttpNotFound();
            }
            ViewBag.Users = GetAvailableUsers(billPayment.Bill);
            ViewBag.SharedPercentage = Enum.GetValues(typeof(SharedPercentage));
            return View("Payment", billPayment);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditPayment (int id, string[] payeeId, string[] sharedPercent, [Bind(Include = "Amount,DatePaid,Payee")] BillPayment billPayment)
        {
            ViewBag.Action = "Edit Payment";
            BillPayment bp = GetBillPayment(id);
            if (bp == null || bp.User.Id != user.Id)
            {
                return HttpNotFound();
            }
            if (ModelState.IsValid)
            {
                bp.Amount = billPayment.Amount;
                bp.DatePaid = billPayment.DatePaid;
                bp.Payee = billPayment.Payee;
                
                db.Entry(bp).State = EntityState.Modified;
                db.SaveChanges();
                UpdateBillPaymentShared(bp, payeeId, sharedPercent);
                db.SaveChanges();
                return RedirectToAction("Details", new { id = bp.Bill.ID });
            }
            ViewBag.Users = GetAvailableUsers(billPayment.Bill);
            ViewBag.SharedPercentage = Enum.GetValues(typeof(SharedPercentage));
            return View("Payment", billPayment);
        }

        public ActionResult DeletePayment (int? id)
        {
            BillPayment billPayment = GetBillPayment(id);
            if (billPayment == null)
            {
                return HttpNotFound();
            }
            Bill bill = billPayment.Bill;
            db.SharedBillPayment.RemoveRange(billPayment.SharedWith);
            db.SaveChanges();
            db.BillPayments.Remove(billPayment);
            db.SaveChanges();
            return RedirectToAction("Details", new { id = bill.ID });
        }

        public ActionResult Paid (int? id, string r = "Details")
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Bill bill = GetBill(id);
            if (bill == null || bill.User.Id != user.Id)
            {
                return HttpNotFound();
            }
            BillPayment billPayment = new BillPayment
            {
                Bill = bill,
                Amount = bill.Amount,
                DatePaid = bill.DueDate,
                Payee = bill.Payee,
                User = db.Users.Find(user.Id)
            };
            
            db.BillPayments.Add(billPayment);
            if (billPayment.Bill.IsShared && billPayment.Bill.SharedWith.Count() > 0)
            {
                GetAvailableUsers(bill).ForEach(x => db.SharedBillPayment.Add(new SharedBillPayment(billPayment, x, bill.SharedWith.Where(y => y.SharedWithUser.Id == x.Id).FirstOrDefault().SharedPercentage)));
            }
            db.Entry(SaveBillForNextPayment(billPayment)).State = EntityState.Modified;
            db.SaveChanges();

MyFinances/Controllers/IncomeUserController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MyFinances.Models;

namespace MyFinances.Controllers
{
    [Authorize]
    public class IncomeUserController : BaseController
    {
        public ActionResult Details (int? id)
        {
            ViewBag.Action = "Details";
            IncomeUser incomeUser = GetIncomeUser(id);
            if (incomeUser == null)
            {
                return HttpNotFound();
            }
            return View(incomeUser);
        }

        public ActionResult Create ()
        {
            ViewBag.Action = "Create";
            IncomeUser incomeUser = new IncomeUser()
            {
                PaymentFrequency = PaymentFrequency.Monthly,
                Date = DateTime.Now
            };
            ViewBag.Users = GetAllAvailableUsers();
            return View("Details", incomeUser);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create (string userId, [Bind(Include = "PaymentFrequency,Date")] IncomeUser incomeUser)
        {
            ViewBag.Action = "Create";
            if (ModelState.IsValid)
            {
                incomeUser.User = db.Users.Find(user.Id);
                incomeUser.PayeeUser = db.Users.Find(userId);
                db.IncomeUsers.Add(incomeUser);
                db.SaveChanges();
                return RedirectToAction("Edit", new { id = incomeUser.ID });
            }
            return View("Details", incomeUser);
        }

        public ActionResult Edit (int? id)
        {
            ViewBag.Action = "Edit";
            IncomeUser incomeUser = GetIncomeUser(id);
            if (incomeUser == null)
            {
                return HttpNotFound();
            }
            ViewBag.Bills = db.Bills.Where(x => x.User.Id == user.Id && x.IsActive).OrderBy(x => x.Name).ToList();
            ViewBag.Loans = db.Loans.Where(x => x.User.Id == user.Id && x.IsActive).OrderBy(x => x.Name).ToList();
            ViewBag.SharedPercentage = Enum.GetValues(typeof(SharedPercentage));
            return View("Details", incomeUser);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit (int[] billId, string[] sharedPercentBill, int[] loanId, string[] sharedPercentLoan, [Bind(Include = "ID,PaymentFrequency,Date")] IncomeUser subIncomeUser)
        {
            ViewBag.Action = "Edit";
            IncomeUser incomeUser = db.IncomeUsers.Find(subIncomeUser.ID);
            if (incomeUser == null)
            {
                return HttpNotFound();
            }
            incomeUser = incomeUser.MapSubmit(subIncomeUser);
            if (ModelState.IsValid)
            {
                db.Entry(incomeUser).State = EntityState.Modified;
                UpdateIncomeUserBills(incomeUser, billId, sharedPercentBill);
                UpdateIncomeUserLoans(incomeUser, loanId, sharedPercentLoan);
                db.SaveChanges();
                return RedirectToAction("Details", new { id = incomeUser.ID });
            }
            ViewBag.Bills = db.Bills.Where(x => x.User.Id == user.Id && x.IsActive).OrderBy(x => x.Name).ToList();
            ViewBag.Loans = db.Loans.Where(x => x.User.Id == user.Id && x.IsActive).OrderBy(x => x.Name).ToList();
            ViewBag.SharedPercentage = Enum.GetValues(typeof(SharedPercentage));
            return View("Details", incomeUser);
        }

        public ActionResult Deactivate (int? id)
        {
            IncomeUser incomeUser = GetIncomeUser(id);
            if (incomeUser == null)
            {
                return HttpNotFound();
            }
            incomeUser.IsActive = false;
            db.Entry(incomeUser).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Activate (int? id)
        {
            IncomeUser incomeUser = GetIncomeUser(id);
            if (incomeUser == null)
            {
                return HttpNotFound();
            }
            incomeUser.IsActive = true;
            db.Entry(incomeUser).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Details", new { id = incomeUser.ID });
        }

        public ActionResult Delete (int? id)
        {
            IncomeUser incomeUser = GetIncomeUser(id);
            if (incomeUser == null)
            {
                return HttpNotFound();
            }
            if (incomeUser.IncomeUserPayments.Any())
            {
                db.IncomeUserPayments.RemoveRange(incomeUser.IncomeUserPayments);
            }
            db.IncomeUsers.Remove(incomeUser);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult AddPayment (int? id)
        {
            ViewBag.Action = "Add Payment";
            IncomeUser incomeUser = GetIncomeUser(id);
            if (incomeUser == null)
            {
                return HttpNotFound();
            }
            NotPaidIncomeUserPayemnt np = incomeUser.NotPaidIncomeUserPayments.OrderBy(x => x.Date).FirstOrDefault();
            IncomeUserPayment payment = new IncomeUserPayment()
            {
                Date = np.Date,
                Amount = np.Amount,
                IncomeUser = incomeUser
            };
            return View("Payment", payment);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddPayment (int? id, [Bind(Include = "Amount,Date,IncomeUser.ID")] IncomeUserPayment incomeUserPayment)
        {
            ViewBag.Action = "Add Payment";
            incomeUserPayment.IncomeUser = GetIncomeUser(id);
            if (incomeUserPayment == null)
            {
                return HttpNotFound();
            }
            if (ModelState.IsValid)
            {
                incomeUserPayment.User = db.Users.Find(user.Id);
                db.IncomeUserPayments.Add(incomeUserPayment);
                db.SaveChanges();
                return RedirectToAction("Details", new { id = incomeUserPayment.IncomeUser.ID });
            }
            return View("Payment", incomeUserPayment);
        }

        public ActionResult EditPayment (int? id)
        {
            ViewBag.Action = "Edit Payment";
            IncomeUserPayment incomeUserPayment = GetIncomeUserPayment(id);
            if (incomeUserPayment == null)
            {
                return HttpNotFound();
            }
            return View("Payment", incomeUserPayment);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditPayment (int id, [Bind(Include = "Amount,Date")] IncomeUserPayment incomeUserPayment)
        {
            ViewBag.Action = "Edit Payment";
            IncomeUserPayment ip = GetIncomeUserPayment(id);
            if (ip == null)
            {
                return HttpNotFound();
            }
            if (ModelState.IsValid)
            {
                ip.Amount = incomeUserPayment.Amount;
                ip.Date = incomeUserPayment.Date;

                db.Entry(ip).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Details", new { id = ip.IncomeUser.ID });
            }
            return View("Payment", incomeUserPayment);
        }

        public ActionResult DeletePayment (int? id)
        {
            IncomeUserPayment incomeUserPayment = GetIncomeUserPayment(id);
            if (incomeUserPayment == null)
            {
                return HttpNotFound();
            }
            IncomeUser incomeUser = incomeUserPayment.IncomeUser;
            db.IncomeUserPayments.Remove(incomeUserPayment);
            db.SaveChanges();
            return RedirectToAction("Details", new { id = incomeUser.ID });
        }
    }
}

MyFinances/Views/IncomeUser/ChoosePrimaryIncome.cshtml
@model MyFinances.Models.PrimaryIncome

@{ ViewBag.Title = ViewBag.Action; }

<div class="clear-after">
    <div class="pull-right">
        @Html.ActionLink("Back to all Incomes", "Index", null, new { @class = "btn btn-primary" })
    </div>
    <h1>@ViewBag.Title</h1>
</div>

<div class="row">
    <div class="col-xs-12 col-md-4">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true)

            <div id="IncomeForm" class="margin-bottom-20">
                <div class="update-form standard">
                    <div class="row">
                        @if ((ViewBag.Incomes as List<MyFinances.Models.Income>).Any())
                        {
                            foreach (MyFinances.Models.Income income in ViewBag.Incomes)
                            {
                                bool incomeChecked = false;
                                if (Model.Income != null)
                                {
                                    incomeChecked = (Model.Income.ID == income.ID);
                                }
                                <div class="col-xs-12 col-md-6">
                                    <div class="form-check">
                                        <input type="radio" name="incomeId" value="@income.ID" class="form-check-input" id="@income.ID" checked="@incomeChecked" />
                                        <label for="@income.ID" class="form-check-label">@income.Name</label>
                                    </div>
                                </div>
                            }
                        }
                    </div>
                </div>
            </div>

            <div class="margin-bottom-20">
                <input type="submit" value="Save" class="btn btn-primary pull-right" />
            </div>
        }
    </div>
</div>

MyFinances/Views/IncomeUser/Payment.cshtml
@model MyFinances.Models.IncomeUserPayment

@{
    string name = Model.IncomeUser.PayeeUser.FirstName + " " + Model.IncomeUser.PayeeUser.LastName;
    ViewBag.Title = ViewBag.Action + " - " + name + " Income User";
}

<div class="clear-after">
    <div class="pull-right">
        @Html.ActionLink("Back to Income", "Details", new { id = Model.IncomeUser.ID }, new { @class = "btn btn-danger" })
    </div>
    <h1>@ViewBag.Title</h1>
</div>

@section Form {
    @Html.HiddenFor(model => model.ID)
    <input type="hidden" name="incomePaymentUserId" id="incomePaymentId" value="@Model.ID" />
    @Html.HiddenFor(model => model.IncomeUser.ID)

    <div class="update-form alert-info">

        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.Date, new { htmlAttributes = new { @class = "control-label" } })
            @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Date)
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.SharedTotal, new { htmlAttributes = new { @class = "control-label" } })
            @Html.EditorFor(model => model.SharedTotal, new { htmlAttributes = new { @class = "form-control", disabled = "disabled", @readonly = "readonly" } })
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Amount, new { htmlAttributes = new { @class = "control-label" } })
            @Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Amount)
        </div>
    </div>
}

@section BelowForm {
    <input type="submit" value="Save" class="btn btn-primary pull-right" />

    @if (ViewBag.Action == "Edit Payment")
    {
        @Html.ActionLink("Delete Payment", "DeletePayment", new { id = Model.ID }, new
        {
            @class = "btn btn-danger confirmation",
            data_confirm_title = "Delete this payment for " + name + " Income User",
            data_confirm_message = "Are you sure you want to delete this payment for " + name + " Income User?",
            data_confirm_style = "danger",
            data_toggle = "tooltip",
            data_placement = "right",
            title = "This will delete this 1 payment."
        })
    }
}

@section Section2 {
    @Html.Partial("_IncomeUserInfo", Model.IncomeUser)

    @{
        bool bills = Model.BillPayments != null && Model.BillPayments.Any();
        bool loans = Model.LoanPayments != null && Model.LoanPayments.Any();
    }

    @if (bills || loans)
    {
        <div class="tab-content margin-bottom-20">
            <div class="table-container">
                <table class="table table-striped">
                    <tbody>
                        @if (bills)
                        {
                            <tr>
                                <th colspan="3">Shared Bills</th>
                            </tr>
                            foreach (MyFinances.Models.SharedBillPayment billPayment in Model.BillPayments)
                            {
                                <tr>
                                    <th>@Html.ActionLink(Html.DisplayFor(x => billPayment.BillPayment.Bill.Name).ToString(), "Details", "Bills", new { ID = billPayment.BillPayment.Bill.ID }, null)</th>
                                    <td>@Html.DisplayFor(x => billPayment.SharedPercentage)</td>
                                    <td class="text-right">@Html.DisplayFor(x => billPayment.Amount)</td>
                                </tr>
                            }
                        }
                        @if (loans)
                        {
                            <tr>
                                <th colspan="3">Shared Loans</th>
                            </tr>
                            foreach (MyFinances.Models.SharedLoanPayment loanPayment in Model.LoanPayments)
                            {
                                <tr>
                                    <th>@Html.ActionLink(Html.DisplayFor(x => loanPayment.LoanPayment.Loan.Name).ToString(), "Details", "Loans", new { ID = loanPayment.LoanPayment.Loan.ID }, null)</th>
                                    <td>@Html.DisplayFor(x => loanPayment.SharedPercentage)</td>
                                    <td class="text-right">@Html.DisplayFor(x => loanPayment.Amount)</td>
                                </tr>
                            }
                        }
                    </tbody>
                </table>
            </div>
        </div>
    }
}

@section Section3 {
    @Html.Partial("_PaymentAverage", Model.IncomeUser)
}

MyFinances/Views/IncomeUser/_IncomeUserInfo.cshtml
@model MyFinances.Models.IncomeUser

@if (ViewBag.Action != "Create")
{
    if (Model.IncomeUserPayments != null && Model.IncomeUserPayments.Any())
    {
        if (Model.IsActive)
        {
            <h2>Last Payment</h2>
            <div class="tab-content margin-bottom-20">
                <div class="table-container alert-success">
                    <table class="table table-striped">
                        <tbody>
                            <tr>
                                <th>@Html.DisplayNameFor(model => model.LastPaymentDate)</th>
                                <td>@Html.DisplayFor(model => model.LastPaymentDate)</td>
                            </tr>
                            <tr>
                                <th>@Html.DisplayNameFor(model => model.LastPaymentAmount)</th>
                                <td>@Html.DisplayFor(model => model.LastPaymentAmount)</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        }
    }
    else
    {
        <p class="alert alert-warning">There are currently no payments for this income user.</p>
    }
}