MyFinances/Controllers/IncomeController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MyFinances.Models;

namespace MyFinances.Controllers
{
    [Authorize]
    public class IncomeController : BaseController
    {
        public ActionResult Index(bool showInactive = false)
        {
            ViewBag.ShowInactive = showInactive;
            ViewBag.PrimaryIncome = GetPrimaryIncome();
            return View(GetIncomes(showInactive));
        }

        public ActionResult Details (int? id)
        {
            ViewBag.Action = "Details";
            Income income = GetIncome(id);
            if (income == null)
            {
                return HttpNotFound();
            }
            return View(income);
        }

        public ActionResult Create ()
        {
            ViewBag.Action = "Create";
            Income income = new Income()
            {
                PaymentFrequency = PaymentFrequency.Monthly,
                Date = DateTime.Now,
                SecondDate = DateTime.Now.AddMonths(1)
            };
            return View("Details", income);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create ([Bind(Include = "Name,PaymentFrequency,Amount,SecondAmount,Date,SecondDate")] Income income)
        {
            ViewBag.Action = "Create";
            if (ModelState.IsValid)
            {
                income.User = db.Users.Find(user.Id);
                db.Incomes.Add(income);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View("Details", income);
        }

        public ActionResult Edit (int? id)
        {
            ViewBag.Action = "Edit";
            Income income = GetIncome(id);
            if (income == null)
            {
                return HttpNotFound();
            }
            return View("Details", income);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit ([Bind(Include = "ID,Name,PaymentFrequency,Amount,SecondAmount,Date,SecondDate")] Income subIncome)
        {
            ViewBag.Action = "Edit";
            Income income = db.Incomes.Find(subIncome.ID);
            if (income == null)
            {
                return HttpNotFound();
            }
            income = income.MapSubmit(subIncome);
            if (ModelState.IsValid)
            {
                db.Entry(income).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Details", new { id = income.ID });
            }
            return View("Details", income);
        }

        public ActionResult Deactivate (int? id)
        {
            Income income = GetIncome(id);
            if (income == null)
            {
                return HttpNotFound();
            }
            income.IsActive = false;
            db.Entry(income).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Activate (int? id)
        {
            Income income = GetIncome(id);
            if (income == null)
            {
                return HttpNotFound();
            }
            income.IsActive = true;
            db.Entry(income).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Details", new { id = income.ID });
        }

        public ActionResult Delete (int? id)
        {
            Income income = GetIncome(id);
            if (income == null)
            {
                return HttpNotFound();
            }
            if (income.IncomePayments.Any())
            {
                db.IncomePayments.RemoveRange(income.IncomePayments);
            }
            db.Incomes.Remove(income);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult ChoosePrimaryIncome ()
        {
            ViewBag.Action = "Choose Primary Income";
            ViewBag.Incomes = GetIncomes(false);
            return View(GetPrimaryIncome());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ChoosePrimaryIncome(int? incomeId)
        {
            ViewBag.Action = "Choose Primary Income";
            PrimaryIncome primaryIncome = GetPrimaryIncome();
            if (ModelState.IsValid && incomeId != null)
            {
                bool newEntry = (primaryIncome.ID == 0);
                primaryIncome.Income = db.Incomes.Find(incomeId);
                primaryIncome.User = db.Users.Find(user.Id);
                if (newEntry)
                {
                    db.PrimaryIncome.Add(primaryIncome);
                } else
                {
                    db.Entry(primaryIncome).State = EntityState.Modified;
                }
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Incomes = GetIncomes(false);
            return View(GetPrimaryIncome());
        }

        public ActionResult AddPayment (int? id)
        {
            ViewBag.Action = "Add Payment";
            Income income = GetIncome(id);
            if (income == null)
            {
                return HttpNotFound();
            }

            IncomePayment payment = new IncomePayment();
            if (income.UseSecond)
            {
                payment.Amount = income.SecondAmount;
                payment.Date = income.SecondDate;
            }
            else
            {
                payment.Amount = income.Amount;
                payment.Date = income.Date;
            }
            payment.Income = income;
            
            return View("Payment", payment);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddPayment (int? id, [Bind(Include = "Amount,Date")] IncomePayment incomePayment)
        {
            ViewBag.Action = "Add Payment";
            incomePayment.Income = GetIncome(id);
            if (incomePayment == null)
            {
                return HttpNotFound();
            }
            if (ModelState.IsValid)
            {
                incomePayment.User = db.Users.Find(user.Id);
                db.IncomePayments.Add(incomePayment);
                db.Entry(SaveIncomeForNextPayment(incomePayment)).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Details", new { id = incomePayment.Income.ID });
            }
            return View("Payment", incomePayment);
        }

        public ActionResult EditPayment (int? id)
        {
            ViewBag.Action = "Edit Payment";
            IncomePayment incomePayment = GetIncomePayment(id);
            if (incomePayment == null)
            {
                return HttpNotFound();
            }
            return View("Payment", incomePayment);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditPayment (int id, [Bind(Include = "Amount,Date")] IncomePayment incomePayment)
        {
            ViewBag.Action = "Edit Payment";
            IncomePayment ip = GetIncomePayment(id);
            if (ip == null)
            {
                return HttpNotFound();
            }
            if (ModelState.IsValid)
            {
                ip.Amount = incomePayment.Amount;
                ip.Date = incomePayment.Date;

                db.Entry(ip).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Details", new { id = ip.Income.ID });
            }
            return View("Payment", incomePayment);
        }

        public ActionResult DeletePayment (int? id)
        {
            IncomePayment incomePayment = GetIncomePayment(id);
            if (incomePayment == null)
            {
                return HttpNotFound();
            }
            Income income = incomePayment.Income;
            db.IncomePayments.Remove(incomePayment);
            db.SaveChanges();
            return RedirectToAction("Details", new { id = income.ID });
        }

        private Income SaveIncomeForNextPayment (IncomePayment incomePayment)
        {
            Income income = incomePayment.Income.Populate(user);
            if (income.Date == incomePayment.Date)
            {
                income.Date = income.GetNextDate(incomePayment.Date);
            }
            else if (income.SecondDate == incomePayment.Date)
            {
                income.SecondDate = income.GetNextSecondDate(incomePayment.Date);
            }

            return income;
        }
    }
}

MyFinances/Controllers/IncomeUserController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MyFinances.Models;

namespace MyFinances.Controllers
{
    [Authorize]
    public class IncomeUserController : BaseController
    {
        public ActionResult Details (int? id)
        {
            ViewBag.Action = "Details";
            IncomeUser incomeUser = GetIncomeUser(id);
            if (incomeUser == null)
            {
                return HttpNotFound();
            }
            return View(incomeUser);
        }

        public ActionResult Create ()
        {
            ViewBag.Action = "Create";
            IncomeUser incomeUser = new IncomeUser()
            {
                PaymentFrequency = PaymentFrequency.Monthly,
                Date = DateTime.Now
            };
            ViewBag.Users = GetAllAvailableUsers();
            return View("Details", incomeUser);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create (string userId, [Bind(Include = "PaymentFrequency,Date")] IncomeUser incomeUser)
        {
            ViewBag.Action = "Create";
            if (ModelState.IsValid)
            {
                incomeUser.User = db.Users.Find(user.Id);
                incomeUser.PayeeUser = db.Users.Find(userId);
                db.IncomeUsers.Add(incomeUser);
                db.SaveChanges();
                return RedirectToAction("Edit", new { id = incomeUser.ID });
            }
            return View("Details", incomeUser);
        }

        public ActionResult Edit (int? id)
        {
            ViewBag.Action = "Edit";
            IncomeUser incomeUser = GetIncomeUser(id);
            if (incomeUser == null)
            {
                return HttpNotFound();
            }
            ViewBag.Bills = db.Bills.Where(x => x.User.Id == user.Id && x.IsActive).OrderBy(x => x.Name).ToList();
            ViewBag.Loans = db.Loans.Where(x => x.User.Id == user.Id && x.IsActive).OrderBy(x => x.Name).ToList();
            ViewBag.SharedPercentage = Enum.GetValues(typeof(SharedPercentage));
            return View("Details", incomeUser);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit (int[] billId, string[] sharedPercentBill, int[] loanId, string[] sharedPercentLoan, [Bind(Include = "ID,PaymentFrequency,Date")] IncomeUser subIncomeUser)
        {
            ViewBag.Action = "Edit";
            IncomeUser incomeUser = db.IncomeUsers.Find(subIncomeUser.ID);
            if (incomeUser == null)
            {
                return HttpNotFound();
            }
            incomeUser = incomeUser.MapSubmit(subIncomeUser);
            if (ModelState.IsValid)
            {
                db.Entry(incomeUser).State = EntityState.Modified;
                UpdateIncomeUserBills(incomeUser, billId, sharedPercentBill);
                UpdateIncomeUserLoans(incomeUser, loanId, sharedPercentLoan);
                db.SaveChanges();
                return RedirectToAction("Details", new { id = incomeUser.ID });
            }
            ViewBag.Bills = db.Bills.Where(x => x.User.Id == user.Id && x.IsActive).OrderBy(x => x.Name).ToList();
            ViewBag.Loans = db.Loans.Where(x => x.User.Id == user.Id && x.IsActive).OrderBy(x => x.Name).ToList();
            ViewBag.SharedPercentage = Enum.GetValues(typeof(SharedPercentage));
            return View("Details", incomeUser);
        }

        public ActionResult Deactivate (int? id)
        {
            IncomeUser incomeUser = GetIncomeUser(id);
            if (incomeUser == null)
            {
                return HttpNotFound();
            }
            incomeUser.IsActive = false;
            db.Entry(incomeUser).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Activate (int? id)
        {
            IncomeUser incomeUser = GetIncomeUser(id);
            if (incomeUser == null)
            {
                return HttpNotFound();
            }
            incomeUser.IsActive = true;
            db.Entry(incomeUser).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Details", new { id = incomeUser.ID });
        }

        public ActionResult Delete (int? id)
        {
            IncomeUser incomeUser = GetIncomeUser(id);
            if (incomeUser == null)
            {
                return HttpNotFound();
            }
            if (incomeUser.IncomeUserPayments.Any())
            {
                db.IncomeUserPayments.RemoveRange(incomeUser.IncomeUserPayments);
            }
            db.IncomeUsers.Remove(incomeUser);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult AddPayment (int? id)
        {
            ViewBag.Action = "Add Payment";
            IncomeUser incomeUser = GetIncomeUser(id);
            if (incomeUser == null)
            {
                return HttpNotFound();
            }
            NotPaidIncomeUserPayemnt np = incomeUser.NotPaidIncomeUserPayments.OrderBy(x => x.Date).FirstOrDefault();
            IncomeUserPayment payment = new IncomeUserPayment()
            {
                Date = np.Date,
                Amount = np.Amount,
                IncomeUser = incomeUser
            };
            return View("Payment", payment);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddPayment (int? id, [Bind(Include = "Amount,Date,IncomeUser.ID")] IncomeUserPayment incomeUserPayment)
        {
            ViewBag.Action = "Add Payment";
            incomeUserPayment.IncomeUser = GetIncomeUser(id);
            if (incomeUserPayment == null)
            {
                return HttpNotFound();
            }
            if (ModelState.IsValid)
            {
                incomeUserPayment.User = db.Users.Find(user.Id);
                db.IncomeUserPayments.Add(incomeUserPayment);
                db.SaveChanges();
                return RedirectToAction("Details", new { id = incomeUserPayment.IncomeUser.ID });
            }
            return View("Payment", incomeUserPayment);
        }

        public ActionResult EditPayment (int? id)
        {
            ViewBag.Action = "Edit Payment";
            IncomeUserPayment incomeUserPayment = GetIncomeUserPayment(id);
            if (incomeUserPayment == null)
            {
                return HttpNotFound();
            }
            return View("Payment", incomeUserPayment);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditPayment (int id, [Bind(Include = "Amount,Date")] IncomeUserPayment incomeUserPayment)
        {
            ViewBag.Action = "Edit Payment";
            IncomeUserPayment ip = GetIncomeUserPayment(id);
            if (ip == null)
            {
                return HttpNotFound();
            }
            if (ModelState.IsValid)
            {
                ip.Amount = incomeUserPayment.Amount;
                ip.Date = incomeUserPayment.Date;

                db.Entry(ip).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Details", new { id = ip.IncomeUser.ID });
            }
            return View("Payment", incomeUserPayment);
        }

        public ActionResult DeletePayment (int? id)
        {
            IncomeUserPayment incomeUserPayment = GetIncomeUserPayment(id);
            if (incomeUserPayment == null)
            {
                return HttpNotFound();
            }
            IncomeUser incomeUser = incomeUserPayment.IncomeUser;
            db.IncomeUserPayments.Remove(incomeUserPayment);
            db.SaveChanges();
            return RedirectToAction("Details", new { id = incomeUser.ID });
        }
    }
}

MyFinances/Views/Income/ChoosePrimaryIncome.cshtml
@model MyFinances.Models.PrimaryIncome

@{ ViewBag.Title = ViewBag.Action; }

<div class="clear-after">
    <div class="pull-right">
        @Html.ActionLink("Back to all Incomes", "Index", null, new { @class = "btn btn-primary" })
    </div>
    <h1>@ViewBag.Title</h1>
</div>

@section Form {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <div class="update-form standard">
        <div class="row">
            @if ((ViewBag.Incomes as List<MyFinances.Models.Income>).Any())
            {
                foreach (MyFinances.Models.Income income in ViewBag.Incomes)
                {
                    bool incomeChecked = false;
                    if (Model.Income != null)
                    {
                        incomeChecked = (Model.Income.ID == income.ID);
                    }
                    <div class="col-xs-12 col-md-6">
                        <div class="form-check">
                            <input type="radio" name="incomeId" value="@income.ID" class="form-check-input" id="@income.ID" checked="@incomeChecked" />
                            <label for="@income.ID" class="form-check-label">@income.Name</label>
                        </div>
                    </div>
                }
            }
        </div>
    </div>
}

@section BelowForm {
    <input type="submit" value="Save" class="btn btn-primary pull-right" />
}

MyFinances/Views/Income/Details.cshtml
@model MyFinances.Models.Income

@{ ViewBag.Title = ((ViewBag.Action != "Create") ? Model.Name : ViewBag.Action) + " Income"; }

<div class="clear-after">
    <div class="pull-right">
        @if (ViewBag.Action == "Edit")
        {
            @Html.ActionLink("Back to Income", "Details", new { ID = Model.ID }, new { @class = "btn btn-danger" })
        }
        else
        {
            @Html.ActionLink("Back to all Incomes", "Index", null, new { @class = "btn btn-primary" })
        }
    </div>
    <h1>@ViewBag.Title</h1>
</div>

@if (ViewBag.Action != "Details")
{
    @section Form {
        @Html.HiddenFor(model => model.ID)
        <div class="update-form standard">

            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true)

            <div class="row">
                <div class="col-xs-12 col-lg-6">
                    <div class="form-group">
                        @Html.LabelFor(model => model.Name, new { @class = "control-label" })
                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Name)
                    </div>
                </div>

                <div class="col-xs-12 col-lg-6">
                    <div class="form-group">
                        @Html.LabelFor(model => model.PaymentFrequency, new { @class = "control-label" })
                        @Html.EnumDropDownListFor(model => model.PaymentFrequency, "Select Payment Frequency", new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.PaymentFrequency)
                    </div>
                </div>
                <div class="clearfix"></div>

                <div class="col-xs-12 col-lg-6">
                    <div class="form-group">
                        @Html.LabelFor(model => model.Date, new { @class = "control-label" })
                        @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Date)
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Amount, new { @class = "control-label" })
                        @Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Amount)
                    </div>
                </div>

                <div class="col-xs-12 col-lg-6">
                    <div class="form-group">
                        @Html.LabelFor(model => model.SecondDate, new { @class = "control-label" })
                        @Html.EditorFor(model => model.SecondDate, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.SecondDate)
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.SecondAmount, new { @class = "control-label" })
                        @Html.EditorFor(model => model.SecondAmount, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.SecondAmount)
                    </div>
                </div>
            </div>
        </div>
    }

    @section BelowForm {
        <input type="submit" value="Save" class="btn btn-primary pull-right" />

        @if (ViewBag.Action == "Edit")
        {
            @Html.ActionLink("Deactivate", "Deactivate", new { id = Model.ID }, new
            {
                @class = "btn btn-danger confirmation",
                data_confirm_title = "Deactivate " + Model.Name + " Bill",
                data_confirm_message = "Are you sure you want to deactivate deactivate " + Model.Name + " Income?",
                data_confirm_style = "danger",
                data_toggle = "tooltip",
                data_placement = "right",
                title = "Will set to NOT active - Payments will NOT be deleted"
            })
        }
    }
}
else
{
    @section Section1 {
        <div class="tab-content margin-bottom-20">
            <div class="table-container">
                <table class="table table-striped">
                    <tbody>
                        @if (Model.UseSecond)
                        {
                            <tr>
                                <th>@Html.DisplayNameFor(model => model.Amount)</th>
                                <td>@Html.DisplayFor(model => model.SecondAmount)</td>
                            </tr>
                            <tr>
                                <th>@Html.DisplayNameFor(model => model.Date)</th>
                                <td>@Html.DisplayFor(model => model.SecondDate)</td>
                            </tr>
                        }
                        else
                        {
                            <tr>
                                <th>@Html.DisplayNameFor(model => model.Amount)</th>
                                <td>@Html.DisplayFor(model => model.Amount)</td>
                            </tr>
                            <tr>
                                <th>@Html.DisplayNameFor(model => model.Date)</th>
                                <td>@Html.DisplayFor(model => model.Date)</td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    }

    @section BelowForm {
        @if (ViewBag.Action != "Create")
        {
            <div class="text-right margin-bottom-20">
                @if (Model.IsActive)
                {
                    @Html.ActionLink("Add Payment", "AddPayment", new { ID = Model.ID }, new { @class = "btn btn-success" })
                    @Html.ActionLink("Edit Income", "Edit", new { ID = Model.ID }, new { @class = "btn btn-primary" })
                }
                else
                {
                    @Html.ActionLink("Delete", "Delete", new { ID = Model.ID }, new
                    {
                        @class = "btn btn-danger confirmation pull-left",
                        data_confirm_title = "Permanently Delete " + Model.Name + " Income",
                        data_confirm_message = "Are you sure you want to permanently delete " + Model.Name + " Income?<br><strong>All payments will be deleted with deletion.</strong>",
                        data_confirm_style = "danger",
                        data_toggle = "tooltip",
                        data_placement = "right",
                        title = "Will delete - Payments WILL BE DELETED"
                    })

                    @Html.ActionLink("Activate", "Activate", new { ID = Model.ID }, new
                    {
                        @class = "btn btn-success confirmation",
                        data_confirm_title = "Activate " + Model.Name + " Income",
                        data_confirm_message = "Are you sure you want to activate " + Model.Name + " Income?",
                        data_confirm_style = "success",
                        data_toggle = "tooltip",
                        data_placement = "left",
                        title = "Set Active"
                    })
                }
            </div>
        }
    }
}

@section Section2 {
    @Html.Partial("_IncomeInfo")
}

@section Section3 {
    @Html.Partial("_PaymentAverage")
}

MyFinances/Views/Income/Index.cshtml
@model IEnumerable<MyFinances.Models.Income>

@{ ViewBag.Title = "Income"; }

<div class="clear-after">
    <div class="pull-right">
        @Html.ActionLink("Add Income from User", "Create", "IncomeUser", null, new { @class = "btn btn-primary" })
        @Html.ActionLink("Add Income", "Create", null, new { @class = "btn btn-primary" })
    </div>
    <h1>@ViewBag.Title</h1>
</div>

<div class="row">
    <div class="col-xs-12">
        @if (Model.Any())
        {
            <div class="tab-content">
                <div class="table-container">
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th>@Html.DisplayNameFor(m => m.Name)</th>
                                <th class="text-right">@Html.DisplayNameFor(m => m.Amount)</th>
                                <th>@Html.DisplayNameFor(m => m.Date)</th>
                                <th>@Html.DisplayNameFor(m => m.DueIn)</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (MyFinances.Models.Income item in Model)
                            {
                                <tr class="@item.Classes">
                                    <th>@Html.ActionLink(Html.DisplayFor(m => item.Name).ToString(), "Details", new { ID = item.ID })</th>
                                    <td class="text-right">
                                        @if (item.UseSecond)
                                        {
                                            @Html.DisplayFor(m => item.SecondAmount)
                                        }
                                        else
                                        {
                                            @Html.DisplayFor(m => item.Amount)
                                        }
                                    </td>
                                    <td>
                                        @if (item.UseSecond)
                                        {
                                            @item.SecondDate.ToString("MMMM - dd")
                                        }
                                        else
                                        {
                                            @item.Date.ToString("MMMM - dd")
                                        }
                                    </td>
                                    <td>@Html.DisplayFor(m => item.DueIn)</td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>

            <div class="margin-top-20 clearfix">
                <div class="pull-right">
                    @if (ViewBag.ShowInactive)
                    {
                        @Html.ActionLink("Hide Inactive", "Index", null, new { @class = "btn btn-primary" })
                    }
                    else
                    {
                        @Html.ActionLink("Show Inactive", "Index", new { showInactive = true }, new { @class = "btn btn-primary" })
                    }
                </div>
                @Html.ActionLink("Chooase Primary Income", "ChoosePrimaryIncome", null, new { @class = "btn btn-success" })
                @if (ViewBag.PrimaryIncome != null && ViewBag.PrimaryIncome.Income != null)
                {
                    @ViewBag.PrimaryIncome.Income.Name
                }
                else
                {
                    <span>No Primary Income Selected</span>
                }
            </div>
        }
        else
        {
            <p>You currently don't have any incomes to show. You can @Html.ActionLink("add an income", "Create").</p>
        }
    </div>
</div>

MyFinances/Views/Income/Payment.cshtml
@model MyFinances.Models.IncomePayment

@{ ViewBag.Title = ViewBag.Action + " - " + Model.Income.Name + " Income"; }

<div class="clear-after">
    <div class="pull-right">
        @Html.ActionLink("Back to Income", "Details", new { id = Model.Income.ID }, new { @class = "btn btn-danger" })
    </div>
    <h1>@ViewBag.Title</h1>
</div>

@section Form {
    @Html.HiddenFor(model => model.ID)
    <input type="hidden" name="incomePaymentId" id="incomePaymentId" value="@Model.ID" />

    <div class="update-form alert-info">

        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.Date, new { htmlAttributes = new { @class = "control-label" } })
            @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Date)
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Amount, new { htmlAttributes = new { @class = "control-label" } })
            @Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Amount)
        </div>
    </div>
}

@section BelowForm {
    <input type="submit" value="Save" class="btn btn-primary pull-right" />

    @if (ViewBag.Action == "Edit Payment")
    {
        @Html.ActionLink("Delete Payment", "DeletePayment", new { id = Model.ID }, new
        {
            @class = "btn btn-danger confirmation",
            data_confirm_title = "Delete this payment for " + Model.Income.Name + " Income",
            data_confirm_message = "Are you sure you want to delete this payment for " + Model.Income.Name + " Income?",
            data_confirm_style = "danger",
            data_toggle = "tooltip",
            data_placement = "right",
            title = "This will delete this 1 payment."
        })
    }
}

@section Section2 {
    @Html.Partial("_IncomeInfo", Model.Income)
}

@section Section3 {
    @Html.Partial("_PaymentAverage", Model.Income)
}